name: concord
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5
  firebase_app_check: ^0.2.1+14
  google_sign_in: ^6.1.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  intl: ^0.19.0
  reorderables: ^0.4.2
  web_socket_channel: ^3.0.2
  geolocator: ^12.0.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^24.2.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/illustrations/LoginLandingGraphic.svg
    - assets/ProfilePageIcons/
    - assets/ProfilePageIcons/WorkoutIcon.svg
    - assets/ProfilePageIcons/DietIcon.svg
    - assets/ProfilePageIcons/PetsIcon.svg
    - assets/ProfilePageIcons/SleepingIcon.svg
    - assets/ProfilePageIcons/SmokingIcon.svg
    - assets/ProfilePageIcons/DrinkingIcon.svg
    - assets/ProfilePageIcons/LoveLanguagesIcon.svg
    - assets/ProfilePageIcons/CommStyleIcons.svg
    - assets/ProfilePageIcons/FamilyPlansIcon.svg
    - assets/ProfilePageIcons/EducationIcon.svg
    - assets/ProfilePageIcons/ZodiacIcon.svg
    - assets/ProfilePageIcons/LookingForIcon.svg
    - assets/ProfilePageIcons/SchoolIcon.svg
    - assets/ProfilePageIcons/CareerIcon.svg
    - assets/ProfilePageIcons/HomeIcon.svg
    - assets/ProfilePageIcons/OrientationIcon.svg
    - assets/ProfilePageIcons/GenderIcon.svg
    - assets/ProfilePageIcons/HeightIcon.svg
    - assets/ProfilePageIcons/OfflineCircleIndicatorIcon.svg
    - assets/ProfilePageIcons/OnlineCircleIndicatorIcon.svg
    - assets/ProfilePageIcons/LocationIcon.svg
    - assets/LowerNavBarIcons/
